source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JSTokenField_Example', :exclusive => true do
  pod "JSTokenField", :path => "../"
end

target 'JSTokenField_Tests', :exclusive => true do
  pod "JSTokenField", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
